let menuVisible = false;

const toggleShowMenu = () => {
    if (menuVisible) {
        select();
    } else {
        document.getElementById('nav').classList = 'responsive';
        menuVisible = true;
    }
}

const select = () => {
    document.getElementById('nav').classList = '';
    menuVisible = false;
}



// script.js
function showPopup(projectId) {
    const popup = document.getElementById('popup');
    const title = document.getElementById('popup-title');
    const description = document.getElementById('popup-description');
    const link = document.getElementById('popup-link');

    // Obtén la información del proyecto según el projectId
    // Por ejemplo, desde un objeto o una matriz de proyectos
    if (projectId === '1') {
        title.textContent = 'HackMX';
        description.textContent = 'Working with Thales in a Hackathon for a problematic that they have. I make a real time 911 transcript that recognize the emotions of the caller with an incorporation of a visualization of where the emergency is';
        link.href = 'https://github.com/AlgoLozano/Lingua_Rescue_THALES.git';
    } else if (projectId === '2') {
        title.textContent = 'CANSAT Competition';
        description.textContent = 'Woking in a Pico size Artificial Satellite, supposed to have a egg and components that would send the information of position, acceleration and velocity of the satellite when it was release from 100m.';
        link.href = 'https://youtu.be/MzjNMM2PnjY';
    }else if (projectId === '3') {
        title.textContent = 'TEC de Monterrey Intel project';
        description.textContent = 'A system that detects the energy consumption of different light bulbs. Compare the brightness and its consumption with reality and what the packaging indicates';
        link.href = 'https://youtu.be/cCLRSpFVNKI?si=wSULW_iH08ogZwsD';
    }else if (projectId === '4') {
        title.textContent = 'TEC de Monterrey John Deere project';
        description.textContent = 'A control system for a DC motor for a scale car. Detect the rpms generated by the motor depending on the speed with an encoder and display it on an LCD';
        link.href = '';
    }else if (projectId === '5') {
        title.textContent = 'Odometry and Pure Pursuit';
        description.textContent = 'The implementation of the Pure Pursuit trajectory tracker is addressed using a combination of software tools widely used in the robotics community. Simulink is used to understand how the algorithm works on the robot and its environment. To then use Python for the generation of trajectories and control calculations, and ROS2 as middleware for communication between the Puzzlebot and the algorithm in real time. The main objective of this practice is to understand how Pure Pursuit works and the communication that exists thanks to the Secure Shell (SSH) and Robot Operating System 2 (ROS2) protocol. Accurate trajectory tracking is a fundamental requirement in many mobile robotics applications, such as autonomous navigation of ground vehicles and manipulation of mobile robots in dynamic environments. This work will provide a solid foundation for future developments in the field of mobile robotics and autonomous navigation.';
        link.href = 'https://youtu.be/6Su8iyZkGvc?si=QeS6gI8tqMWY2_Ke';
    }else if (projectId === '6') {
        title.textContent = 'Colore detection';
        description.textContent = 'Its focus on the implementation of computer vision for color detection by a camera connected to a Jetson. Elder brother. The main objective is to develop an algorithm that allows us to detect specific colors through filters with the help of Python, OpenCV and ROS2 to acquire the information given by the camera. Color-based object detection and localization is an essential task for many robotic systems, as it allows specific objects to be identified and tracked in the environment, thus facilitating the execution of tasks such as manipulation, autonomous navigation, and visual inspection. At the end of the practice, everything done will allow us to demonstrate the efficiency and precision of color identification, as well as the variety of applications in robotic systems. This work will give us a new fundamental branch, computational vision, which will help us have solid future foundations on developments in safe and efficient autonomous navigation.';
        link.href = 'https://youtu.be/tHcYEWP-yoo?si=QZxx8tu9uj9DXwUy';
    }else if (projectId === '7') {
        title.textContent = 'FPGA project';
        description.textContent = 'It is a video game called Battleship programmed with an FPGA and controlled by a DPAD. The DPAD sensor helps us be the control to choose the squares to attack.';
        link.href = 'https://youtu.be/Ah-KeqRJUk8';
    }else if (projectId === '8') {
        title.textContent = 'IOT Mosquitto project';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://youtu.be/H4rZ798AjVA?si=4YOAyKtAKgO0hQ9v';
    }

    popup.style.display = 'block';
}

function closePopup() {
    const popup = document.getElementById('popup');
    popup.style.display = 'none';
}
