let menuVisible = false;

const toggleShowMenu = () => {
    if (menuVisible) {
        select();
    } else {
        document.getElementById('nav').classList = 'responsive';
        menuVisible = true;
    }
}

const select = () => {
    document.getElementById('nav').classList = '';
    menuVisible = false;
}



// script.js
function showPopup(projectId) {
    const popup = document.getElementById('popup');
    const title = document.getElementById('popup-title');
    const description = document.getElementById('popup-description');
    const link = document.getElementById('popup-link');

    // Obtén la información del proyecto según el projectId
    // Por ejemplo, desde un objeto o una matriz de proyectos
    if (projectId === '1') {
        title.textContent = 'HackMX';
        description.textContent = 'Descripción del Proyecto 1...';
        link.href = 'https://www.ejemplo1.com';
    } else if (projectId === '2') {
        title.textContent = 'CANSAT Competition';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://www.ejemplo1.com';
    }else if (projectId === '3') {
        title.textContent = 'TEC de Monterrey Intel project';
        description.textContent = 'A system that detects the energy consumption of different light bulbs. Compare the brightness and its consumption with reality and what the packaging indicates';
        link.href = 'https://www.ejemplo1.com';
    }else if (projectId === '4') {
        title.textContent = 'TEC de Monterrey John Deere project';
        description.textContent = 'A control system for a DC motor for a scale car. Detect the rpms generated by the motor depending on the speed with an encoder and display it on an LCD';
        link.href = 'https://miscompetenciastec21.tec.mx/elumen/StudentAchievements?actionMethod=portfolio##4707515';
    }else if (projectId === '5') {
        title.textContent = 'Odometry and Pure Pursuit';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://www.ejemplo1.com';
    }else if (projectId === '6') {
        title.textContent = 'Colore detection';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://www.ejemplo1.com';
    }else if (projectId === '7') {
        title.textContent = 'FPGA project';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://www.ejemplo1.com';
    }else if (projectId === '8') {
        title.textContent = 'IOT Mosquitto project';
        description.textContent = 'Descripción del Proyecto 2...';
        link.href = 'https://www.ejemplo1.com';
    }

    popup.style.display = 'block';
}

function closePopup() {
    const popup = document.getElementById('popup');
    popup.style.display = 'none';
}
